name: CI

on: [push, pull_request]

env:
  SECRET_KEY: z+-mvm&4a=g=3o38k8lsg4nl37a#(nd%e3m=0+216_%)x5bcgq
  ALLOWED_HOSTS: localhost,127.0.0.1
  DEBUG: False
  DATABASE_URL: postgres://djhl_db:djhl_db@localhost:5433/djhl_db
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes -r requirements.txt
      - name: psycopg2 prerequisites
        run: sudo apt-get install python-dev libpq-dev
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: '12.3'
          postgres db: djhl_db
          postgres user: djhl_db
          postgres password: djhl_db    
      - name: Code Quality
        run: |
          pip install black
          black -l 120 -S --check
      - name: Test Code
        run: |
          pip install pytest pytest-django
          pytest
